const ACCESS_KEY = 'alfaTasks.accessGranted';
const ACTIVE_TASKS_KEY = 'alfaTasks.activeTasks';
const CONSENT_KEY = 'alfaTasks.termsConsent';
// Версия редакции документов (Соглашение + Политика). При изменении согласие запрашивается заново.
const TERMS_VERSION = '2026-09-17';

const rewards = {
  small: { id: 'small', label: 'до 2 000 ₽', caption: 'Более доступный', product: 'Дебетовая карта', productAccusative: 'дебетовую карту', link: 'https://alfa.me/dx3_ke' },
  large: { id: 'large', label: 'до 4 000 ₽', caption: 'Менее доступный', product: 'Кредитная карта', productAccusative: 'кредитную карту', link: 'https://alfa.me/oUT1ol', ageRestricted: true },
};

// Пошаговая инструкция для каждого варианта награды:
// Вариант 01 (small) — дебетовая карта, Вариант 02 (large) — кредитная карта.
const instructionPlans = {
  small: {
    product: 'Дебетовая карта',
    cta: 'Оформить дебетовую карту',
    steps: [
      'Оформи дебетовую карту Альфа-Банк по ссылке',
      'Прими доставку продукта в удобное время',
      'Активируй карту, совершив любую покупку этой картой от 1 рубля (переводы не считаются)',
      'После этого зайди в личный кабинет и напиши отзыв под заданием',
      'Готово! В течение 3-4 дней награда поступит на вашу карту',
    ],
    note: 'P.S. ЕСЛИ ТЕБЕ МЕНЬШЕ 18, ТО ПОТРЕБУЕТСЯ ЭЛЕКТРОННОЕ ПОДТВЕРЖДЕНИЕ ОТ РОДИТЕЛЯ',
  },
  large: {
    product: 'Кредитная карта',
    cta: 'Оформить кредитную карту',
    steps: [
      'Оформи кредитную карту Альфа-Банк по ссылке',
      'Прими доставку продукта в удобное время',
      'Активируй карту, совершив любую покупку этой картой от 1 рубля (переводы не считаются)',
      'После этого зайди в личный кабинет и напиши отзыв под заданием',
      'Готово! В течение 3-4 дней награда поступит на вашу карту',
    ],
    note: '',
  },
};

const REVIEW_MIN_LENGTH = 10;

const iconPaths = {
  shield: '<path d="M12 3.5 19 6v5.2c0 4.4-2.7 7.5-7 9.3-4.3-1.8-7-4.9-7-9.3V6l7-2.5Z"/><path d="m8.6 12 2.2 2.2 4.6-4.7"/>',
  arrowRight: '<path d="M5 12h14"/><path d="m13 6 6 6-6 6"/>', arrowLeft: '<path d="M19 12H5"/><path d="m11 18-6-6 6-6"/>',
  arrowUpRight: '<path d="M5 19 19 5"/><path d="M9 5h10v10"/>', lock: '<rect x="5" y="10" width="14" height="10" rx="2"/><path d="M8 10V7.5a4 4 0 0 1 8 0V10"/><path d="M12 14v2"/>',
  star: '<path d="m12 3 2.8 5.7 6.2.9-4.5 4.4 1.1 6.2-5.6-2.9-5.6 2.9 1.1-6.2L3 9.6l6.2-.9L12 3Z"/>',
  quote: '<path d="M8.5 7H6.8A2.8 2.8 0 0 0 4 9.8v2.4A2.8 2.8 0 0 0 6.8 15h.4A2.8 2.8 0 0 0 10 12.2V9.7A2.7 2.7 0 0 0 7.3 7Z"/><path d="M16.5 7h-1.7a2.8 2.8 0 0 0-2.8 2.8v2.4a2.8 2.8 0 0 0 2.8 2.8h.4a2.8 2.8 0 0 0 2.8-2.8V9.7A2.7 2.7 0 0 0 15.3 7Z"/>',
  reviews: '<path d="M4.5 5.2A2.2 2.2 0 0 1 6.7 3h10.6A2.2 2.2 0 0 1 19.5 5.2v8.1a2.2 2.2 0 0 1-2.2 2.2H12l-4.2 3.6v-3.6H6.7a2.2 2.2 0 0 1-2.2-2.2V5.2Z"/><path d="m12 6.1.85 1.75 1.93.28-1.4 1.36.33 1.92L12 10.5l-1.71.91.33-1.92-1.4-1.36 1.93-.28L12 6.1Z"/>',
  grid: '<rect x="4" y="4" width="6" height="6" rx="1.2"/><rect x="14" y="4" width="6" height="6" rx="1.2"/><rect x="4" y="14" width="6" height="6" rx="1.2"/><rect x="14" y="14" width="6" height="6" rx="1.2"/>', user: '<circle cx="12" cy="8" r="3.3"/><path d="M5.5 20a6.5 6.5 0 0 1 13 0"/>', check: '<path d="m5 12 4.2 4.2L19 6.5"/>', info: '<circle cx="12" cy="12" r="8.5"/><path d="M12 11.2v5"/><path d="M12 8h.01"/>', spark: '<path d="m12 3 1.2 5.8L19 10l-5.8 1.2L12 17l-1.2-5.8L5 10l5.8-1.2L12 3Z"/><path d="m19 16 .5 2.5L22 19l-2.5.5L19 22l-.5-2.5L19 16Z"/>', wallet: '<path d="M4 7.5A2.5 2.5 0 0 1 6.5 5H19v14H6.5A2.5 2.5 0 0 1 4 16.5v-9Z"/><path d="M4 8h15"/><path d="M16 12h5v4h-5a2 2 0 0 1 0-4Z"/><path d="M17.5 14h.01"/>', clock: '<circle cx="12" cy="12" r="8.5"/><path d="M12 7v5l3 2"/>', link: '<path d="M10 13.8 8.4 15.4a3.2 3.2 0 0 1-4.6-4.6l2.7-2.7a3.2 3.2 0 0 1 4.6 0"/><path d="m14 10.2 1.6-1.6a3.2 3.2 0 0 1 4.6 4.6l-2.7 2.7a3.2 3.2 0 0 1-4.6 0"/><path d="m8.5 12.5 7-5"/>',
  close: '<path d="M6.5 6.5 17.5 17.5"/><path d="M17.5 6.5 6.5 17.5"/>'
};

function icon(name, size = 20, className = '') { return `<svg class="${className}" width="${size}" height="${size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${iconPaths[name] || ''}</svg>`; }
function escapeHTML(value = '') { return String(value).replace(/[&<>'"]/g, c => ({ '&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;' })[c]); }
function getTelegramUser() { const fallback={firstName:'Гость',lastName:'',username:'telegram_user',photoUrl:'',isTelegram:false}; try { const telegram=window.Telegram?.WebApp; telegram?.ready?.(); telegram?.expand?.(); const u=telegram?.initDataUnsafe?.user; if(!u)return fallback; return {firstName:u.first_name||'Пользователь',lastName:u.last_name||'',username:u.username||'',photoUrl:u.photo_url||'',isTelegram:true}; } catch { return fallback; } }
function getDisplayName(user){return [user.firstName,user.lastName].filter(Boolean).join(' ')||'Пользователь';}
function getUsername(user){return user.username?`@${user.username.replace(/^@/,'')}`:'@username';}
function getInitials(user){return ([user.firstName,user.lastName].filter(Boolean).map(p=>p.trim().charAt(0)).join('')||'A').slice(0,2).toUpperCase();}
function safePhotoUrl(url){try{const p=new URL(url);return ['http:','https:'].includes(p.protocol)?escapeHTML(p.href):'';}catch{return '';}}
function avatarMarkup(user,size=''){const photo=safePhotoUrl(user.photoUrl);const cls=`avatar${size?` ${size}`:''}`;return `<span class="${cls}">${photo?`<img src="${photo}" alt="" />`:escapeHTML(getInitials(user))}</span>`;}
function loadActiveTasks(){try{const s=JSON.parse(localStorage.getItem(ACTIVE_TASKS_KEY)||'[]');return Array.isArray(s)?s:[];}catch{return [];}}
function saveActiveTasks(tasks){try{localStorage.setItem(ACTIVE_TASKS_KEY,JSON.stringify(tasks));}catch{}}
function formatDate(timestamp){try{return new Intl.DateTimeFormat('ru-RU',{day:'numeric',month:'short'}).format(new Date(timestamp));}catch{return 'сегодня';}}
const user=getTelegramUser();
function readAccessFlag(){try{return localStorage.getItem(ACCESS_KEY)==='true';}catch{return false;}}
const state={mode:readAccessFlag()&&readConsent()?'app':'gate',view:'tasks',selectedReward:null,activeTasks:loadActiveTasks(),history:[],modal:null,dir:'none',consent:readConsent()};
const app=document.querySelector('#app'); const toast=document.querySelector('#toast'); let toastTimer;
function showToast(message){if(!toast)return;window.clearTimeout(toastTimer);toast.textContent=message;toast.classList.add('visible');toastTimer=window.setTimeout(()=>toast.classList.remove('visible'),3200);}
function persistAccess(){try{localStorage.setItem(ACCESS_KEY,'true');}catch{}}
function readConsent(){try{return localStorage.getItem(CONSENT_KEY)===TERMS_VERSION;}catch{return false;}}
function persistConsent(){try{localStorage.setItem(CONSENT_KEY,TERMS_VERSION);}catch{}}
function haptic(kind){try{const hb=window.Telegram?.WebApp?.HapticFeedback;if(!hb)return;if(kind==='success'||kind==='error'||kind==='warning')hb.notificationOccurred(kind);else hb.impactOccurred(kind||'light');}catch{}}
function viewClass(){if(state.dir==='forward')return 'view-enter view-enter-forward';if(state.dir==='back')return 'view-enter view-enter-back';return 'view-enter';}
function scrollTopInstant(){try{const el=document.documentElement;const prev=el.style.scrollBehavior;el.style.scrollBehavior='auto';el.scrollTop=0;if(document.body)document.body.scrollTop=0;el.style.scrollBehavior=prev||'';}catch{}}
function motionOK(){try{return window.matchMedia&&window.matchMedia('(prefers-reduced-motion: no-preference)').matches;}catch{return false;}}
function flowProgress(step){const segs=[1,2,3].map(i=>`<span class="flow-seg${i<=step?' on':''}"${i===step?' aria-current="step"':''}></span>`).join('');return `<div class="flow-progress" role="group" aria-label="Шаг ${step} из 3">${segs}</div>`;}
function avatarButton(){return `<button class="header-profile-button" type="button" data-action="nav-account" aria-label="Открыть личный кабинет"><span class="header-profile-name">${escapeHTML(getDisplayName(user))}</span>${avatarMarkup(user)}</button>`;}
function renderLegalFooter(){return `<footer class="legal-footer"><button class="legal-trigger" type="button" data-action="open-legal" aria-haspopup="dialog">Правовая информация</button></footer>`;}
function renderLegalDoc(){return `<div class="legal-summary"><p><strong>Кратко.</strong> Это независимый частный сервис, а не официальный сайт или приложение АО «Альфа-Банк». Ссылки здесь — партнёрские (реферальные). «Награда» за задания — добровольная выплата администратора сервиса, а не банка. Условия банковских продуктов проверяйте на официальном сайте банка и читайте документы до подписания. Полные тексты — в двух документах ниже.</p></div>
<div class="legal-doc-actions"><button class="legal-doc-card" type="button" data-action="open-terms"><span><strong>Соглашение с условиями сервиса</strong><small>полная юридически значимая редакция · включая порядок выплат «награды» (раздел 4)</small></span>${icon('arrowRight',16)}</button><button class="legal-doc-card" type="button" data-action="open-privacy"><span><strong>Политика конфиденциальности</strong><small>какие данные обрабатываются, где хранятся и как их удалить</small></span>${icon('arrowRight',16)}</button></div>`;}
function renderTermsDoc(){return `<div class="legal-summary"><p><strong>О документе.</strong> Настоящее Соглашение имеет юридическую силу: проставляя отметку согласия на экране входа (либо продолжая использовать Сервис), пользователь принимает его в полном объёме. Обратите внимание на раздел 4 — он описывает порядок выплат «награды», в том числе случаи, когда администратор вправе в выплате отказать.</p></div>
<h3>1. Статус сервиса</h3>
<p>1.1. Сервис «tasks» (далее — «Сервис», «администратор») является независимым информационным ресурсом частного лица, работающим в формате Telegram Mini App.</p>
<p>1.2. Сервис <strong>не является официальным сайтом</strong>, мобильным приложением, разделом, сервисом, программой лояльности или иным продуктом АО «Альфа-Банк» (ОГРН 1027700067328, ИНН 7728168971, официальный сайт: alfabank.ru; далее — «Банк»), а равно любой иной кредитной, финансовой или иной организации.</p>
<p>1.3. Сервис не состоит с Банком в отношениях аффилированности, агентских, трудовых, корпоративных или иных правоотношений, за исключением стандартного участия администратора в общедоступной партнёрской (реферальной) программе Банка на одинаковых для всех участников условиях. Банк не создавал, не одобрял, не спонсирует и не администрирует Сервис.</p>
<p>1.4. Все материалы, оценки и формулировки, размещённые на Сервисе, выражают частное мнение администратора и не могут трактоваться как официальная позиция либо заявление Банка.</p>
<h3>2. Товарные знаки и интеллектуальные права</h3>
<p>2.1. Товарные знаки, знаки обслуживания, логотипы, фирменные и коммерческие обозначения «Альфа-Банк», «Alfa-Bank», «Альфа» и сходные с ними до степени смешения обозначения являются результатами интеллектуальной деятельности АО «Альфа-Банк» и/или аффилированных с ним лиц и охраняются законодательством Российской Федерации (статьи 1477, 1484 ГК РФ).</p>
<p>2.2. Упоминание указанных обозначений на Сервисе носит исключительно информационный (номинативный) характер — для обозначения соответствующего банковского продукта, переход к оформлению которого осуществляется по внешней ссылке, — не представляет их как собственные обозначения Сервиса и не преследует цели введения пользователей в заблуждение относительно источника банковских услуг.</p>
<p>2.3. Если вы являетесь правообладателем и полагаете, что ваши права нарушены, направьте администратору мотивированное уведомление (п. 11.4): спорный материал будет проверен и при обоснованности требований незамедлительно изменён или удалён.</p>
<h3>3. Партнёрские (реферальные) ссылки</h3>
<p>3.1. Ссылки на оформление банковских продуктов, размещённые на Сервисе, являются партнёрскими (реферальными). Оформление продукта пользователь осуществляет самостоятельно и непосредственно на официальном ресурсе Банка, на условиях и в порядке, которые определяет исключительно Банк.</p>
<p>3.2. Администратор может получать от Банка и/или его партнёров вознаграждение за привлечённых клиентов. Такое вознаграждение выплачивается не за счёт пользователя, не увеличивает для него стоимость продуктов и услуг и не изменяет условия его обслуживания.</p>
<p>3.3. Материалы Сервиса могут содержать рекламу и/или партнёрские ссылки в смысле законодательства о рекламе.</p>
<h3>4. «Награда» и выплаты пользователям</h3>
<p>4.1. Упоминаемая на Сервисе «награда» является добровольным стимулирующим вознаграждением, которое выплачивает администратор Сервиса из собственных средств (в том числе за счёт получаемого им партнёрского вознаграждения) при условии добросовестного и полного выполнения пользователем всех условий задания.</p>
<p>4.2. Выплата «награды» <strong>не является платежом, премией, кешбэком, процентом или иной выплатой АО «Альфа-Банк»</strong>. Банк в таких выплатах не участвует, их не гарантирует и не несёт за них ответственности; требования, связанные с «наградой», не могут быть предъявлены Банку. В свою очередь администратор не отвечает за действия и решения Банка, включая отказ в выдаче продукта, тарифы и сроки.</p>
<p>4.3. Указанные суммы («до …») являются максимально возможными и зависят от фактически подтверждённого результата. Ориентировочный срок зачисления после успешной проверки — до 3–4 рабочих дней; срок носит оценочный характер и не является гарантией. Администратор вправе отказать в выплате при невыполнении условий задания, недобросовестности, злоупотреблении, накрутке, предоставлении недостоверных сведений либо нарушении настоящих условий.</p>
<p>4.4. Решение о выплате «награды» в каждом конкретном случае администратор принимает самостоятельно и по своему усмотрению. Пользователь соглашается, что администратор вправе не выплачивать «награду» полностью или частично <strong>без объяснения причин</strong>, в том числе если, по разумной оценке администратора, задание выполнено не полностью, недобросовестно или с нарушением настоящего Соглашения, а также если партнёрское вознаграждение за оформленный пользователем продукт не поступило администратору. Отказ в выплате не требует от администратора раскрытия мотивов и не может рассматриваться как нарушение настоящего Соглашения; обязательство произвести выплату возникает у администратора лишь при положительном решении по соответствующему заданию.</p>
<h3>5. Отсутствие финансовых услуг; характер информации</h3>
<p>5.1. Сервис не является кредитной организацией, банковским агентом, оператором по приёму платежей, платёжным агентом, посредником или представителем Банка, не оказывает банковских, финансовых, страховых, брокерских, инвестиционных, консультационных и иных лицензируемых услуг и не заключает сделок от имени третьих лиц.</p>
<p>5.2. Информация о банковских продуктах носит справочно-информационный характер, может быть неполной или устаревшей и не заменяет официальные документы Банка. Актуальные условия, тарифы, требования и риски изложены на официальном сайте Банка (alfabank.ru) и в договорах Банка, которые пользователь обязан самостоятельно изучить до заключения договора.</p>
<p>5.3. Ничто на Сервисе не является публичной офертой (статьи 435, 437 ГК РФ), обещанием вознаграждения, индивидуальной инвестиционной рекомендацией или предложением о заключении кредитного либо иного договора.</p>
<h3>6. Отзывы пользователей</h3>
<p>6.1. Размещая отзыв, пользователь заявляет и гарантирует, что отзыв отражает его личный реальный опыт, не содержит недостоверных сведений, оскорблений, персональных данных третьих лиц, сведений ограниченного доступа и иной информации, распространение которой запрещено законодательством Российской Федерации.</p>
<p>6.2. Пользователь безвозмездно, без ограничения территории и на время размещения отзыва предоставляет администратору неисключительное право использования текста отзыва в рамках работы Сервиса. Пользователь вправе удалить отзыв, очистив данные Сервиса на своём устройстве.</p>
<p>6.3. Администратор вправе не публиковать, отклонить или удалить отзыв без объяснения причин. Заказные, фиктивные, вводящие в заблуждение отзывы запрещены и не вознаграждаются.</p>
<h3>7. Персональные данные и конфиденциальность</h3>
<p>7.1. Сервис не запрашивает и не обрабатывает банковские и платёжные данные (номера карт, сроки действия, CVV/CVC, пароли, коды из SMS, реквизиты документов). Никому не сообщайте такие данные, даже если запрос поступил якобы от имени Сервиса.</p>
<p>7.2. Технические данные профиля Telegram (имя, имя пользователя, фотография) используются исключительно для отображения интерфейса, не передаются третьим лицам и не сохраняются на сторонних серверах. Статусы заданий и тексты отзывов хранятся локально на устройстве пользователя (localStorage) и могут быть удалены пользователем в любой момент.</p>
<p>7.3. Персональные данные, вводимые при оформлении банковского продукта, пользователь предоставляет непосредственно Банку на его официальном ресурсе; их обработка осуществляется Банком в соответствии с Федеральным законом от 27.07.2006 № 152-ФЗ «О персональных данных» и политикой конфиденциальности Банка. Сервис не является ни оператором этих данных, ни их получателем.</p>
<p>7.4. Состав обрабатываемых данных, цели и пределы их обработки, порядок удаления данных и отзыва согласия подробнее описаны в Политике конфиденциальности, являющейся неотъемлемой частью настоящего Соглашения.</p>
<h3>8. Ограничение ответственности</h3>
<p>8.1. Сервис предоставляется «как есть» (as is) и «как доступно», без каких-либо явных или подразумеваемых гарантий, включая гарантии бесперебойности работы, отсутствия ошибок, соответствия ожиданиям и достижения пользователем какого-либо результата.</p>
<p>8.2. В максимальном объёме, допускаемом законодательством Российской Федерации, администратор не несёт ответственности за: действия и решения Банка и третьих лиц (включая отказ в выдаче продукта, изменение тарифов, сроки доставки, прекращение или изменение партнёрских программ); содержание внешних сайтов, на которые ведут ссылки; технические сбои Telegram, хостинг-провайдера и сетей связи; прямые и косвенные убытки и упущенную выгоду, возникшие в связи с использованием или невозможностью использования Сервиса.</p>
<p>8.3. Пользователь самостоятельно оценивает условия и риски и несёт полную ответственность за свои решения о заключении договоров с Банком.</p>
<h3>9. Возрастные и иные ограничения</h3>
<p>9.1. Отдельные задания (в том числе связанные с кредитными продуктами) доступны только полностью дееспособным лицам в возрасте 18 лет и старше, о чём указано в интерфейсе. Подтверждая «мне 18+», пользователь заявляет и гарантирует соответствие этому требованию.</p>
<p>9.2. Несовершеннолетний, участвующий в иных заданиях, подтверждает наличие надлежащего согласия законного представителя на совершение соответствующих юридически значимых действий; при оформлении банковских продуктов такое согласие оформляется в порядке, предусмотренном Банком (в том числе в электронной форме).</p>
<h3>10. Отсутствие связи с Telegram</h3>
<p>10.1. Сервис не является продуктом Telegram, не спонсируется, не поддерживается и не администрируется Telegram. Telegram не несёт ответственности за содержание и работу Сервиса.</p>
<h3>11. Применимое право, порядок принятия условий, изменение условий и разрешение споров</h3>
<p>11.1. К настоящему Соглашению и отношениям сторон применяется законодательство Российской Федерации.</p>
<p>11.2. Используя Сервис (в том числе переходя по размещённым на нём ссылкам), пользователь подтверждает, что прочитал, понял и безоговорочно принимает настоящее Соглашение в полном объёме. При входе в Сервис согласие дополнительно подтверждается отметкой в поле «Ознакомлен(а) и согласен(на) с документами сервиса»; проставление отметки является акцептом настоящего Соглашения и Политики конфиденциальности и фиксируется локально на устройстве пользователя. Несогласие с условиями означает обязанность прекратить использование Сервиса.</p>
<p>11.3. Администратор вправе в одностороннем внесудебном порядке изменять настоящее Соглашение; актуальная редакция всегда доступна в данном разделе. Продолжение использования Сервиса после изменения условий означает принятие новой редакции; при существенных изменениях согласие может запрашиваться повторно.</p>
<p>11.4. Канал связи для вопросов, уведомлений правообладателей и претензий — через бота/профиль Telegram, из которого был открыт данный Mini App. Споры разрешаются в досудебном (претензионном) порядке; срок ответа на претензию — до 30 (тридцати) календарных дней с даты её получения. При недостижении согласия спор передаётся на рассмотрение суда в соответствии с законодательством Российской Федерации.</p>
<p class="legal-updated">Редакция Соглашения от 17 сентября 2026 г. АО «Альфа-Банк»: ОГРН 1027700067328, ИНН 7728168971; официальный сайт — alfabank.ru. Сервис «tasks» не аффилирован с банком (см. раздел 1).</p>`;}
function renderPrivacyDoc(){return `<div class="legal-summary"><p><strong>Совсем коротко.</strong> Сервис обрабатывает минимум данных: имя, @username и фото из профиля Telegram нужны только чтобы показать их в интерфейсе, а статусы заданий, текст отзыва и отметка согласия хранятся на вашем же устройстве. Банковские и платёжные данные Сервис не запрашивает никогда.</p></div>
<h3>1. Общие положения</h3>
<p>1.1. Настоящая Политика конфиденциальности (далее — «Политика») описывает, какие данные обрабатываются при использовании Сервиса «tasks» (далее — «Сервис»), в каком объёме и с какими целями. Политика является неотъемлемой частью Соглашения с условиями сервиса.</p>
<p>1.2. Политика составлена с учётом положений Федерального закона от 27.07.2006 № 152-ФЗ «О персональных данных». Оператором данных в объёме, описанном настоящей Политикой, является администратор Сервиса (далее — «Администратор»).</p>
<p>1.3. Отмечая пункт «Ознакомлен(а) и согласен(на) с документами сервиса» на экране входа, пользователь подтверждает ознакомление с Политикой и согласие с ней. Продолжая использовать Сервис без отметки (для пользователей, получивших доступ ранее), пользователь подтверждает ознакомление фактическими действиями.</p>
<h3>2. Состав обрабатываемых данных</h3>
<p>2.1. <strong>Данные профиля Telegram:</strong> имя (и фамилия, если указаны), имя пользователя (@username) и фотография профиля, автоматически передаваемые средой Telegram Mini App. Они используются исключительно для отображения интерфейса (приветствие, шапка, личный кабинет) и на серверы Администратора не передаются.</p>
<p>2.2. <strong>Данные, хранимые локально:</strong> отметка согласия с документами, статусы заданий и текст отправленного отзыва сохраняются в хранилище браузера (localStorage) на устройстве пользователя и за пределы этого устройства не передаются.</p>
<p>2.3. <strong>Технические данные среды:</strong> Сервис использует стандартные возможности Telegram Web App (тема оформления, размеры окна, тактильный отклик); отдельно от Telegram Администратор такие данные не собирает и не хранит.</p>
<h3>3. Данные, которые Сервис не запрашивает</h3>
<p>3.1. Сервис не запрашивает и не обрабатывает банковские и платёжные данные: номера карт, сроки действия, CVV/CVC, пароли, коды из SMS, реквизиты документов. Никому не сообщайте такие данные, даже если запрос поступил якобы от имени Сервиса.</p>
<p>3.2. Данные, вводимые пользователем при оформлении банковского продукта, предоставляются непосредственно АО «Альфа-Банк» на его официальном ресурсе и обрабатываются Банком в соответствии с его собственной политикой конфиденциальности и законодательством Российской Федерации. Сервис не является ни оператором этих данных, ни их получателем.</p>
<h3>4. Цели обработки</h3>
<p>4.1. Отображение интерфейса Сервиса (имя и аватар пользователя) и работа личного кабинета (перечень заданий, их статусы, текст отзыва).</p>
<p>4.2. Фиксация факта ознакомления пользователя с документами Сервиса (отметка согласия) — без передачи этой информации за пределы устройства пользователя.</p>
<h3>5. Передача данных третьим лицам</h3>
<p>5.1. Данные, указанные в разделе 2, третьим лицам не передаются: они обрабатываются локально на устройстве пользователя. Серверного хранения профилей, статусов заданий и отзывов у Администратора нет.</p>
<p>5.2. Администратор не контролирует обработку данных самим Telegram (при использовании Mini App) и Банком (при оформлении продукта по ссылке из Сервиса) — их политики применяются самостоятельно.</p>
<h3>6. Хранение, удаление и отзыв согласия</h3>
<p>6.1. Локальные данные хранятся до тех пор, пока пользователь не удалит их. Для этого достаточно очистить данные сайта в настройках браузера либо Telegram — все данные Сервиса (включая текст отзыва и отметку согласия) будут удалены безвозвратно.</p>
<p>6.2. Пользователь вправе в любой момент отозвать согласие, прекратив использование Сервиса и удалив локальные данные (п. 6.1).</p>
<h3>7. Права пользователя</h3>
<p>7.1. Пользователь вправе знать состав и способы обработки своих данных, требовать их уточнения, блокирования или уничтожения, а также отозвать согласие на обработку.</p>
<p>7.2. Поскольку данные Сервиса хранятся локально, все перечисленные действия пользователь выполняет самостоятельно средствами своего устройства (п. 6.1); обращения к Администратору для этого не требуются.</p>
<h3>8. Изменения Политики</h3>
<p>8.1. Администратор вправе изменять Политику в одностороннем порядке; актуальная редакция всегда доступна в данном разделе Сервиса. При существенных изменениях согласие с новой редакцией запрашивается повторно при входе в Сервис.</p>
<h3>9. Контакты</h3>
<p>9.1. Вопросы, замечания и запросы, связанные с обработкой данных, направляются через бота/профиль Telegram, из которого был открыт данный Mini App. Срок рассмотрения обращения — до 30 (тридцати) календарных дней.</p>
<p class="legal-updated">Редакция от 17 сентября 2026 г. Применяется вместе с Соглашением с условиями сервиса (раздел «Правовая информация»).</p>`;}
function renderGate(){return `<div class="gate-screen"><div class="gate-top"><div class="brand-lockup"><span class="brand-mark">А</span><span class="brand-text"><strong class="brand-service">tasks</strong></span><span class="mini-pill">MINI APP</span></div></div><main class="gate-main"><div class="gate-kicker">Задания с наградой</div><h1 class="gate-title">Твой следующий<br /><em>шаг — здесь.</em></h1><p class="gate-description">Выполняй простые задания, выбирай свой уровень и получай вознаграждение. Начнём с одного вопроса.</p><section class="gate-card" aria-labelledby="eligibility-question"><div class="gate-card-label"><span>Проверка участия</span><strong>01 / 01</strong></div><h2 class="gate-question" id="eligibility-question">Вы когда-нибудь были клиентом Альфа-Банка?</h2><div class="gate-actions"><button class="button button-dark button-full" type="button" data-action="eligible-yes">Да, являюсь или являлся(ась)</button><button class="button button-outline button-full" type="button" data-action="eligible-no">Нет, не являюсь</button></div><div class="consent-block" id="consent-block" role="group" aria-label="Согласие с документами сервиса"><div class="consent-row"><input class="consent-check" type="checkbox" id="consent-check" data-action="toggle-consent"${state.consent?' checked':''} /><label class="consent-text" for="consent-check">Ознакомлен(а) и согласен(на) с документами сервиса</label></div><div class="consent-links"><button class="consent-link" type="button" data-action="open-terms">Условия сервиса</button><span class="consent-sep" aria-hidden="true">·</span><button class="consent-link" type="button" data-action="open-privacy">Политика конфиденциальности</button></div></div></section></main><div class="gate-bottom"><div class="gate-footer">${icon('shield',17)}<span>Ответ нужен только для проверки условий участия</span></div>${renderLegalFooter()}</div></div>`;}
function renderRejected(){return `<div class="rejected-screen"><div class="gate-top"><div class="brand-lockup"><span class="brand-mark">А</span><span class="brand-text"><strong class="brand-service">tasks</strong></span></div></div><main class="rejected-content"><div class="rejected-icon">${icon('shield',38)}</div><h1 class="rejected-title">Участие пока недоступно</h1><p class="rejected-description">К сожалению, в этой активности могут участвовать только люди, которые никогда не были клиентами Альфа-Банка.</p><button class="button button-dark" type="button" data-action="back-to-gate">Вернуться к ответу</button></main><div class="gate-bottom"><div class="gate-footer">${icon('info',17)}<span>Если ответ был выбран случайно, его можно изменить</span></div>${renderLegalFooter()}</div></div>`;}
function renderAppHeader(){return `<header class="app-header"><button class="header-brand" type="button" data-action="nav-tasks" aria-label="На главный экран"><span class="brand-mark">А</span><span class="brand-text"><strong class="brand-service">tasks</strong></span></button>${avatarButton()}</header>`;}
function renderTaskHome(){return `<section class="${viewClass()}" aria-labelledby="tasks-heading"><div class="welcome-row"><div><div class="eyebrow">Твоя подборка</div><h1 class="view-heading" id="tasks-heading">Задания<br />с наградой</h1></div><span class="status-pill">Онлайн</span></div><div class="balance-card"><span class="balance-shine" aria-hidden="true"></span><div class="balance-copy"><span class="balance-label">Максимальная награда</span><strong class="balance-amount">до 4 000 ₽</strong><span class="balance-note">Выбери задание и начни<br />сегодня</span></div><div class="balance-orb">${icon('spark',27)}</div></div><div class="section-heading"><h2>Все задания</h2><span>1 доступно · 3 скоро</span></div><div class="task-list"><button class="task-card task-card-available" type="button" data-action="open-reviews" aria-label="Открыть задание Отзывы"><div class="task-card-main"><span class="task-icon">${icon('reviews',25)}</span><span class="task-card-copy"><span class="task-meta"><span>Доступно сейчас</span><span>${icon('arrowUpRight',13)}</span></span><span class="task-card-bottomless"><strong class="task-card-title">Отзывы</strong><span class="task-card-description">Оцени качество курьерской службы, а также процесс оформления фирменных продуктов Альфа-банка и получи награду! Вместе мы сможем повысить качество сервиса ❤️</span></span></span></div><div class="task-card-bottom"><span>Простое задание</span><span class="arrow">Открыть ${icon('arrowRight',13)}</span></div></button><div class="locked-grid"><div class="locked-card task-card locked" data-action="locked-soon"><span class="task-icon dark">${icon('grid',19)}</span><h3>Опрос</h3><p>Поделись своим мнением</p><span class="coming-soon">${icon('lock',12)} Скоро</span></div><div class="locked-card task-card locked" data-action="locked-soon"><span class="task-icon dark">${icon('wallet',19)}</span><h3>Финансы</h3><p>Полезные сценарии</p><span class="coming-soon">${icon('lock',12)} Скоро</span></div><div class="locked-card task-card locked" data-action="locked-soon"><span class="task-icon dark">${icon('user',19)}</span><h3>Пригласи друга</h3><p>Скоро в приложении</p><span class="coming-soon">${icon('lock',12)} Скоро</span></div></div></div></section>`;}
function renderDetailTopbar(label='Задание'){return `<div class="detail-topbar"><button class="icon-button" type="button" data-action="back-step" aria-label="Назад">${icon('arrowLeft',19)}</button><div class="eyebrow">${escapeHTML(label)}</div></div>`;}
function renderIntro(){return `<section class="${viewClass()}"><div class="detail-topbar"><button class="icon-button" type="button" data-action="back-step" aria-label="Назад">${icon('arrowLeft',19)}</button><div class="eyebrow">Задание 01</div></div>${flowProgress(1)}<div class="detail-hero"><div class="detail-hero-content"><div class="eyebrow">Доступно сейчас</div><h1>Отзывы</h1><p>Один шаг, чтобы поделиться своим опытом и получить награду.</p></div><div class="detail-hero-icon">${icon('reviews',30)}</div></div><div class="info-card intro-card"><h2>${icon('info',19)} Перед началом</h2><div class="intro-copy"><p>Мы платим за вашу обратную связь касаемо нашего сервиса, в который входит процесс доставки продукта и сопровождение клиента на всех начальных этапах.</p><p class="intro-lead">${icon('star',16)}<span>Оставьте отзыв и заберите награду</span></p></div><div class="info-note">${icon('spark',15)}<span><strong>Один человек может получить награду сразу за два варианта</strong> — пройдите оба задания и забирайте обе выплаты.</span></div></div><div class="detail-actions"><button class="button button-full" type="button" data-action="to-rewards">Далее — выбрать награду ${icon('arrowRight',17)}</button></div></section>`;}
function renderRewards(){return `<section class="${viewClass()}"><div class="detail-topbar"><button class="icon-button" type="button" data-action="back-step" aria-label="Назад">${icon('arrowLeft',19)}</button><div class="eyebrow">Шаг 02</div></div>${flowProgress(2)}<div class="reward-intro"><div class="eyebrow">Выбор уровня</div><h1 class="view-heading">Какую награду<br />выбираешь?</h1><p class="view-subheading">Выбери подходящий вариант. После этого откроется инструкция и ссылка на задание.</p></div><div class="reward-list"><button class="reward-option" type="button" data-action="choose-reward" data-reward="small"><span class="reward-option-copy"><span>Вариант 01 · Дебетовая карта</span><strong>до 2 000 ₽</strong><small>Более доступный</small></span><span class="reward-option-mark">${icon('arrowRight',19)}</span></button><button class="reward-option" type="button" data-action="choose-reward" data-reward="large"><span class="reward-option-copy"><span>Вариант 02 · Кредитная карта</span><strong>до 4 000 ₽</strong><small>Менее доступный <b class="age-badge">18+</b></small></span><span class="reward-option-mark">${icon('arrowRight',19)}</span></button></div></section>`;}
function renderAgeGate(){return `<section class="${viewClass()} age-gate-view"><div class="detail-topbar"><button class="icon-button" type="button" data-action="back-step" aria-label="Назад">${icon('arrowLeft',19)}</button><div class="eyebrow">Проверка возраста</div></div><div class="info-card age-gate-card"><div class="detail-hero-icon">${icon('shield',30)}</div><h1>Вам уже исполнилось 18 лет?</h1><p>Этот вариант доступен только пользователям 18 лет и старше.</p><div class="gate-actions"><button class="button button-full" type="button" data-action="age-yes">Да, мне 18+</button><button class="button button-outline button-full" type="button" data-action="age-no">Нет, мне нет 18</button></div></div></section>`;}
function renderInstructions(){const reward=rewards[state.selectedReward]||rewards.small;const plan=instructionPlans[reward.id]||instructionPlans.small;const steps=plan.steps.map((step,index)=>`<li class="step-item"><span class="step-number">${String(index+1).padStart(2,'0')}</span><p>${escapeHTML(step)}</p></li>`).join('');return `<section class="${viewClass()}"><div class="detail-topbar"><button class="icon-button" type="button" data-action="back-step" aria-label="Назад">${icon('arrowLeft',19)}</button><div class="eyebrow">Шаг 03</div></div>${flowProgress(3)}<div class="instruction-heading"><div class="eyebrow">Пошаговая инструкция</div><h1 class="view-heading">Почти готово<br />к старту.</h1><span class="selected-reward">${icon('wallet',14)} ${escapeHTML(plan.product)} · награда ${escapeHTML(reward.label)}</span></div><div class="info-card"><h2>${icon('check',19)} Что нужно сделать</h2><p>Пять шагов: оформить карту по ссылке, принять доставку, активировать её покупкой и написать отзыв в личном кабинете. Награда поступит на карту после проверки отзыва.</p><ol class="step-list">${steps}</ol>${plan.note?`<div class="step-note">${icon('info',15)}<p>${escapeHTML(plan.note)}</p></div>`:''}</div><div class="detail-actions"><a class="button button-full" href="${reward.link}" target="_blank" rel="noopener noreferrer" data-action="start-task" data-reward="${reward.id}">Перейти к заданию ${icon('arrowUpRight',17)}</a><button class="button button-ghost button-full" type="button" data-action="back-step">Выбрать другой уровень</button></div><div class="external-hint">${icon('link',13)} Ссылка откроется в новой вкладке</div></section>`;}
function activeTaskById(taskId){return state.activeTasks.find(task=>task.id===taskId)||null;}
function taskStage(task){return task&&task.stage==='under-review'?'under-review':'progress';}
function reviewIsValid(value){return String(value||'').trim().replace(/\s+/g,' ').length>=REVIEW_MIN_LENGTH;}
function renderActiveTask(task){const reward=rewards[task.rewardId]||rewards.small;const plan=instructionPlans[reward.id]||instructionPlans.small;const underReview=taskStage(task)==='under-review';return `<article class="active-task-card"><div class="active-task-top"><span class="active-task-icon">${icon('reviews',20)}</span><div class="active-task-copy"><h3>${escapeHTML(task.title||'Отзывы')}</h3><p>${escapeHTML(plan.product)} · добавлено ${escapeHTML(formatDate(task.createdAt))}</p></div><span class="task-status${underReview?' is-review':''}">${underReview?'Отзыв на проверке':'В процессе'}</span></div>${underReview?`<div class="task-review-block">${icon('quote',15)}<div><span>Твой отзыв</span><p>${escapeHTML(task.review||'')}</p></div></div>`:''}<div class="active-task-bottom"><span class="active-task-reward">Награда: <strong>${escapeHTML(reward.label)}</strong></span><a class="button button-ghost" href="${reward.link}" target="_blank" rel="noopener noreferrer">Продолжить ${icon('arrowUpRight',14)}</a></div>${underReview?`<div class="task-waiting">${icon('clock',16)}<span>Отзыв проверяется: награда поступит на карту в течение 3-4 дней.</span></div>`:`<div class="active-task-actions"><button class="button button-full" type="button" data-action="task-done" data-task="${escapeHTML(task.id)}">${icon('check',17)} Выполнил</button><p class="active-task-hint">Нажми «Выполнил», когда карта оформлена, доставлена и активирована покупкой от 1 ₽</p></div>`}</article>`;}
function renderModalSheet(content){return `<div class="modal-overlay" data-action="close-modal"><div class="modal-sheet" role="dialog" aria-modal="true" aria-labelledby="modal-title"><div class="modal-grabber" aria-hidden="true"></div><button class="modal-close" type="button" data-action="close-modal" aria-label="Закрыть">${icon('close',16)}</button>${content}</div></div>`;}
function renderModal(){const modal=state.modal;if(!modal)return '';
 if(modal.type==='waiting'){return renderModalSheet(`<div class="modal-icon is-success">${icon('check',26)}</div><div class="modal-kicker">Отзыв отправлен</div><h2 class="modal-title" id="modal-title">Отзыв проверяется</h2><p class="modal-text">Награда скоро будет у вас: мы проверим отзыв и отправим вознаграждение на карту. Обычно это занимает 3-4 дня.</p><div class="modal-note is-success">${icon('spark',15)}<span>Статус задания уже обновлён в личном кабинете.</span></div><div class="modal-actions"><button class="button button-full" type="button" data-action="close-modal">Готово</button></div>`);}
 if(modal.type==='legal'){return renderModalSheet(`<div class="modal-icon is-muted">${icon('shield',26)}</div><div class="modal-kicker">Неофициальный сервис · важно</div><h2 class="modal-title" id="modal-title">Правовая информация</h2><div class="legal-doc">${renderLegalDoc()}</div>`);}
 if(modal.type==='terms'){return renderModalSheet(`<div class="modal-icon is-muted">${icon('shield',26)}</div><div class="modal-kicker">Документ сервиса · юридически значимая редакция</div><h2 class="modal-title" id="modal-title">Соглашение с условиями сервиса</h2><div class="legal-doc">${renderTermsDoc()}</div>`);}
 if(modal.type==='privacy'){return renderModalSheet(`<div class="modal-icon is-muted">${icon('shield',26)}</div><div class="modal-kicker">Документ сервиса</div><h2 class="modal-title" id="modal-title">Политика конфиденциальности</h2><div class="legal-doc">${renderPrivacyDoc()}</div>`);}
 const task=activeTaskById(modal.taskId);if(!task)return '';const reward=rewards[task.rewardId]||rewards.small;const plan=instructionPlans[reward.id]||instructionPlans.small;
 if(modal.type==='done'){return renderModalSheet(`<div class="modal-icon">${icon('check',26)}</div><div class="modal-kicker">Проверка условий</div><h2 class="modal-title" id="modal-title">Ты получил карту и совершил с ней покупку?</h2><p class="modal-text">Для награды нужно оформить ${escapeHTML(reward.productAccusative)} по ссылке, принять доставку и активировать её любой покупкой от 1 рубля. Переводы не считаются.</p><div class="modal-actions"><button class="button button-full" type="button" data-action="done-yes">Да, всё выполнено</button><button class="button button-outline button-full" type="button" data-action="done-no">Нет, ещё нет</button></div>`);}
 if(modal.type==='wait'){return renderModalSheet(`<div class="modal-icon is-muted">${icon('clock',26)}</div><div class="modal-kicker">Пока рано</div><h2 class="modal-title" id="modal-title">Нужно дождаться выполнения условий</h2><p class="modal-text">Награда начисляется только после того, как ${escapeHTML(plan.product.toLowerCase())} оформлена по ссылке, доставлена и активирована покупкой от 1 рубля. Переводы не считаются.</p><div class="modal-note">${icon('info',15)}<span>Вернись в личный кабинет и нажми «Выполнил» снова, когда карта будет активирована.</span></div><div class="modal-actions"><a class="button button-full" href="${reward.link}" target="_blank" rel="noopener noreferrer">${escapeHTML(plan.cta)} ${icon('arrowUpRight',16)}</a><button class="button button-ghost button-full" type="button" data-action="close-modal">Понятно, продолжу позже</button></div>`);}
 if(modal.type==='review'){return renderModalSheet(`<div class="modal-icon">${icon('quote',26)}</div><div class="modal-kicker">Условия выполнены</div><h2 class="modal-title" id="modal-title">Напиши отзыв под заданием</h2><p class="modal-text">Расскажи, как прошли оформление, доставка и активация карты. Отзыв появится в личном кабинете под этим заданием.</p><label class="review-field" for="review-text"><span>Твой отзыв</span><textarea class="review-input" id="review-text" name="review" rows="5" maxlength="1200" placeholder="Например: оформил карту за пару минут, курьер привёз в удобное время, активировал покупкой на 1 ₽ в тот же день…">${escapeHTML(modal.draft||'')}</textarea></label><div class="modal-actions"><button class="button button-full" type="button" data-action="submit-review">Прикрепить отзыв ${icon('arrowRight',16)}</button><button class="button button-ghost button-full" type="button" data-action="close-modal">Отмена</button></div>`);}
 return '';}
function renderAccount(){const displayName=getDisplayName(user),username=getUsername(user),tasks=state.activeTasks,profileLabel=user.isTelegram?'Профиль Telegram':'Демо-профиль';return `<section class="${viewClass()}" aria-labelledby="account-heading"><div class="account-heading"><div class="eyebrow">Личный кабинет</div><h1 class="view-heading" id="account-heading">Твой профиль</h1><p class="view-subheading">Здесь собраны данные профиля и задания, которые ты уже начал.</p></div><div class="profile-card">${avatarMarkup(user,'large')}<div class="profile-card-copy"><span class="profile-label">${profileLabel}</span><h2>${escapeHTML(displayName)}</h2><p>${escapeHTML(username)}</p></div></div><div class="account-section"><div class="account-section-heading"><h2>Задания в процессе</h2><span class="task-count">${tasks.length}</span></div>${tasks.length?tasks.map(renderActiveTask).join(''):`<div class="empty-state"><div class="empty-state-icon">${icon('clock',21)}</div><h3>Пока здесь пусто</h3><p>Выбери задание на главной, чтобы оно появилось в этом разделе.</p></div>`}</div><div class="account-footnote">${icon('shield',14)}<span>Данные профиля берутся из Telegram Mini App. В обычном браузере показан демо-профиль.</span></div></section>`;}
function renderBottomNav(){const onAccount=state.view==='account',tasksCount=state.activeTasks.length;return `<nav class="bottom-nav" aria-label="Основная навигация"><button class="nav-item${onAccount?'':' active'}" type="button" data-action="nav-tasks"${onAccount?'':' aria-current="page"'} aria-label="Задания">${icon('grid',21)}<span>Задания</span>${tasksCount?`<span class="nav-badge">${tasksCount}</span>`:''}</button><button class="nav-item${onAccount?' active':''}" type="button" data-action="nav-account"${onAccount?' aria-current="page"':''} aria-label="Личный кабинет">${icon('user',21)}<span>Кабинет</span></button></nav>`;}
function renderApp(){let content=renderTaskHome();if(state.view==='account')content=renderAccount();if(state.view==='intro')content=renderIntro();if(state.view==='rewards')content=renderRewards();if(state.view==='ageGate')content=renderAgeGate();if(state.view==='instructions')content=renderInstructions();return `<div class="app-shell">${renderAppHeader()}<main class="app-main">${content}${renderLegalFooter()}</main>${renderBottomNav()}</div>`;}
/* Модалка живёт отдельно от оболочки: открытие/закрытие окна не перерисовывает
   экран под ней — контент не «мигает» и не проигрывает анимацию заново. */
function setModalBodyClass(){try{document.body.classList.toggle('modal-open',!!state.modal);}catch{}}
/* Правовая модалка доступна на любом экране (даже на гейте, до входа в приложение) */
function syncModal(){const modalType=state.modal&&state.modal.type;const html=(state.mode==='app'||modalType==='legal'||modalType==='terms'||modalType==='privacy')?renderModal():'';let host=document.getElementById('modal-root');if(html){if(!host){host=document.createElement('div');host.id='modal-root';document.body.appendChild(host);}host.innerHTML=html;}else if(host){host.remove();}}
function render(){setModalBodyClass();if(state.mode==='gate'){app.innerHTML=renderGate();syncModal();state.dir='none';return;}if(state.mode==='rejected'){app.innerHTML=renderRejected();syncModal();state.dir='none';return;}app.innerHTML=renderApp();syncModal();state.dir='none';}
function renderModalOnly(){setModalBodyClass();syncModal();}
function closeModal(){if(!state.modal)return;const overlay=document.querySelector('#modal-root .modal-overlay');if(overlay&&!overlay.classList.contains('is-closing')&&motionOK()){state.modal.closing=true;overlay.classList.add('is-closing');window.setTimeout(()=>{if(state.modal&&state.modal.closing){state.modal=null;renderModalOnly();}},260);}else{state.modal=null;renderModalOnly();}}
function go(view){if(state.view===view)return;state.history.push(state.view);state.view=view;state.dir='forward';scrollTopInstant();render();}
function back(){const previous=state.history.pop();state.view=previous||'tasks';state.dir=previous?'back':'none';scrollTopInstant();render();}
function addTaskToProgress(rewardId){const reward=rewards[rewardId]||rewards.small;const taskId=`reviews-${reward.id}`;if(!state.activeTasks.find(task=>task.id===taskId)){state.activeTasks.unshift({id:taskId,title:'Отзывы',rewardId:reward.id,createdAt:Date.now(),stage:'progress'});}saveActiveTasks(state.activeTasks);haptic('success');showToast('Задание добавлено в личный кабинет');}
document.addEventListener('click',event=>{const target=event.target.closest('[data-action]');if(!target)return;const action=target.dataset.action;switch(action){
case 'eligible-yes':state.mode='rejected';scrollTopInstant();render();break;
case 'eligible-no':{if(!state.consent){haptic('warning');showToast('Сначала отметьте согласие с документами сервиса');const block=document.getElementById('consent-block');if(block){block.classList.remove('is-attention');void block.offsetWidth;block.classList.add('is-attention');try{block.scrollIntoView({block:'nearest',behavior:motionOK()?'smooth':'auto'});}catch{}}break;}persistConsent();persistAccess();state.mode='app';state.view='tasks';state.history=[];state.modal=null;scrollTopInstant();render();break;}
case 'open-terms':haptic('light');state.modal={type:'terms'};renderModalOnly();break;
case 'open-privacy':haptic('light');state.modal={type:'privacy'};renderModalOnly();break;
case 'toggle-consent':{state.consent=!!target.checked;if(state.consent){haptic('light');const block=document.getElementById('consent-block');if(block)block.classList.remove('is-attention');}break;}
case 'back-to-gate':state.mode='gate';scrollTopInstant();render();break;
case 'nav-tasks':state.mode='app';state.view='tasks';state.history=[];state.modal=null;scrollTopInstant();render();break;
case 'nav-account':state.mode='app';state.view='account';state.history=[];state.modal=null;scrollTopInstant();render();break;
case 'locked-soon':haptic('light');showToast('Этот раздел откроется позже');break;
case 'open-legal':haptic('light');state.modal={type:'legal'};renderModalOnly();break;
case 'open-reviews':go('intro');break;
case 'back-step':back();break;
case 'to-rewards':go('rewards');break;
case 'choose-reward':{const rewardId=target.dataset.reward||'small';if(rewardId==='large'){state.selectedReward='large';go('ageGate');}else{state.selectedReward=rewardId;go('instructions');}break;}
case 'age-yes':go('instructions');break;
case 'age-no':haptic('error');showToast('Этот вариант доступен только с 18 лет');break;
case 'start-task':addTaskToProgress(target.dataset.reward||state.selectedReward||'small');render();break;
case 'task-done':{const taskId=target.dataset.task||'';const task=activeTaskById(taskId);if(!task){showToast('Задание не найдено, обнови страницу');break;}state.modal={type:taskStage(task)==='under-review'?'waiting':'done',taskId};renderModalOnly();break;}
case 'done-yes':state.modal={type:'review',taskId:state.modal&&state.modal.taskId||'',draft:state.modal&&state.modal.draft||''};renderModalOnly();break;
case 'done-no':state.modal={type:'wait',taskId:state.modal&&state.modal.taskId||''};renderModalOnly();break;
case 'submit-review':{const modal=state.modal||{};const task=activeTaskById(modal.taskId);if(!task){state.modal=null;render();break;}const field=document.querySelector('#review-text');const text=String(field&&field.value||'').trim();if(!reviewIsValid(text)){haptic('error');showToast(`Опиши отзыв чуть подробнее — минимум ${REVIEW_MIN_LENGTH} символов`);if(field)field.focus();break;}task.review=text.slice(0,1200);task.reviewAt=Date.now();task.stage='under-review';saveActiveTasks(state.activeTasks);haptic('success');state.modal={type:'waiting',taskId:task.id};render();break;}
case 'close-modal':if(target.classList.contains('modal-overlay')&&event.target!==target)break;closeModal();break;
default:break;}});
document.addEventListener('keydown',event=>{if(event.key==='Escape')closeModal();});
document.addEventListener('input',event=>{if(state.modal&&state.modal.type==='review'&&event.target&&event.target.id==='review-text')state.modal.draft=event.target.value;});
/* Лёгкая вибрация при нажатии на интерактивные элементы (в Telegram) */
document.addEventListener('pointerdown',event=>{try{if(event.target&&event.target.closest&&event.target.closest('.button,.task-card,.reward-option,.nav-item,.icon-button,.header-brand,.header-profile-button,.locked-card,.modal-close,.legal-trigger,.consent-link,.legal-doc-card,.consent-check'))haptic('light');}catch{}},{capture:true,passive:true});
/* Жест «свайп от левого края вправо» = вернуться назад, как в нативных приложениях */
let edgeSwipe=null;
function canSwipeBack(){return state.mode==='app'&&!state.modal&&state.history.length>0;}
document.addEventListener('touchstart',event=>{edgeSwipe=null;if(!canSwipeBack())return;const touch=event.touches&&event.touches[0];if(touch&&touch.clientX<=28)edgeSwipe={x:touch.clientX,y:touch.clientY,dx:0,dy:0};},{passive:true});
document.addEventListener('touchmove',event=>{if(!edgeSwipe)return;const touch=event.touches&&event.touches[0];if(!touch)return;edgeSwipe.dx=touch.clientX-edgeSwipe.x;edgeSwipe.dy=touch.clientY-edgeSwipe.y;if(edgeSwipe.dx<=0||Math.abs(edgeSwipe.dy)>edgeSwipe.dx)return;const main=document.querySelector('.app-main');if(!main)return;main.style.transition='none';main.style.transform=`translateX(${Math.min(edgeSwipe.dx*0.55,96)}px)`;main.style.opacity=String(Math.max(0.55,1-edgeSwipe.dx/380));},{passive:true});
function endEdgeSwipe(){if(!edgeSwipe)return;const dx=edgeSwipe.dx,dy=edgeSwipe.dy;edgeSwipe=null;const main=document.querySelector('.app-main');if(main){main.style.transition='transform 200ms cubic-bezier(0.22,1,0.36,1), opacity 200ms ease';main.style.transform='';main.style.opacity='';window.setTimeout(()=>{main.style.transition='';},230);}if(dx>72&&Math.abs(dy)<64&&canSwipeBack())back();}
document.addEventListener('touchend',endEdgeSwipe,{passive:true});
document.addEventListener('touchcancel',endEdgeSwipe,{passive:true});
/* Шторка модалки тянется вниз пальцем (за «ручку» или за верхнюю часть) */
let sheetDrag=null;
document.addEventListener('pointerdown',event=>{sheetDrag=null;const sheet=event.target&&event.target.closest&&event.target.closest('.modal-sheet');if(!sheet)return;const fromGrabber=!!event.target.closest('.modal-grabber');if(!fromGrabber){if(event.target.closest('textarea,input,button,a'))return;if(sheet.scrollTop>0)return;}sheetDrag={sheet,id:event.pointerId,startY:event.clientY,dy:0,active:false};});
document.addEventListener('pointermove',event=>{if(!sheetDrag||event.pointerId!==sheetDrag.id)return;sheetDrag.dy=event.clientY-sheetDrag.startY;if(sheetDrag.dy>10){sheetDrag.active=true;sheetDrag.sheet.classList.remove('snap-back');sheetDrag.sheet.style.transition='none';sheetDrag.sheet.style.transform=`translateY(${sheetDrag.dy}px)`;}});
function endSheetDrag(){if(!sheetDrag)return;const sheet=sheetDrag.sheet,dy=sheetDrag.dy,active=sheetDrag.active;sheetDrag=null;if(!active)return;if(dy>110){sheet.style.transform='';closeModal();}else{sheet.classList.add('snap-back');sheet.style.transform='';window.setTimeout(()=>{sheet.classList.remove('snap-back');sheet.style.transition='';},260);}}
document.addEventListener('pointerup',endSheetDrag);
document.addEventListener('pointercancel',endSheetDrag);
function renderFatal(error){const message=error&&(error.message||String(error))||'Неизвестная ошибка';const target=app||document.body;target.innerHTML=`<div class="gate-screen"><main class="gate-main"><div class="gate-kicker">Что-то пошло не так</div><h1 class="gate-title">Приложение<br /><em>не загрузилось</em></h1><p class="gate-description">Проверь интернет-соединение и обнови страницу. Если ошибка повторится, открой Mini App заново из Telegram.</p><p class="gate-description">Код ошибки: ${escapeHTML(message)}</p><button class="button button-dark button-full" type="button" onclick="location.reload()">Обновить страницу</button></main></div>`;}
try{render();}catch(error){renderFatal(error);}