services:
  - type: web
    name: alfa-tasks
    runtime: static
    plan: free
    buildCommand: "true"
    staticPublishPath: .
    headers:
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /index.html
        name: Cache-Control
        value: no-cache, no-store, must-revalidate
      - path: /*.js
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.css
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
